# API Configuration
base.url=http://localhost:3000/api/v1
api.timeout=10
api.connect.timeout=5

# Use WireMock for testing
use.wiremock=true
wiremock.port=3000

# Database Configuration
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/banking_loan_db
db.username=postgres
db.password=rules
db.port=5432
db.schema=banking

# Report Configuration
report.path=./test-reports/
report.name=LoanManagementAPI_Report